### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by JustNojusPS4** [1Emin/Growtopia-Proxy#1]
Proxy not working
![image](https://user-images.githubusercontent.com/44664356/152157970-068784f5-615c-43bd-99d2-a1625a213410.png)

**Comment by 1Emin** [comment]
> Proxy not working ![image](https://user-images.githubusercontent.com/44664356/152157970-068784f5-615c-43bd-99d2-a1625a213410.png)

Change port :)

Open and "Ctrl+F" Search : 17255 and change all to 17250 (or another working proxy)

**Comment by 1Emin** [comment]
If you get error more please write me : Sahyui#1337

**Comment by aurhack** [comment]
how to fix proxy at this day?

**Comment by aurhack** [comment]
![image](https://user-images.githubusercontent.com/72323046/175322497-d2544d80-b0a1-42e4-b7db-8a4e1df86f45.png)
